apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-simulator
  namespace: solar-prod
  labels:
    app: solar-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-simulator
  template:
    metadata:
      labels:
        app: solar-simulator
    spec:
      containers:
      - name: solar-simulator
        image: solar-simulator:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
