apiVersion: v1
kind: Service
metadata:
  name: solar-simulator
  namespace: solar-prod
  labels:
    app: solar-simulator
spec:
  selector:
    app: solar-simulator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
